places=['Berlin','Grecia', 'Francia', 'Japon']
print(places)
print(sorted(places))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
print(f"There are {len(places)} here!")